# Generated by Django 3.1.5 on 2021-04-06 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210404_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Relation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.datetime.today)),
                ('category', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                
            ],
        ),
    ]
