# Generated by Django 3.1.5 on 2021-04-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customer_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_form',
            new_name='Contact1',
        ),
    ]
