# Generated by Django 3.1.5 on 2021-04-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_contact1_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact1',
            name='customer',
        ),
    ]
